tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"
tap "zaquestion/tap"
brew "openssl"
brew "sqlite"
brew "python"
brew "asciinema"
brew "bat"
brew "cmake"
brew "direnv"
brew "python@2"
brew "fontforge"
brew "fzf"
brew "jasper"
brew "gifsicle"
brew "git"
brew "git-cal"
brew "gnupg"
brew "htop"
brew "hub"
brew "imagemagick"
brew "jpegoptim"
brew "jq"
brew "mysql"
brew "neovim", args: ["HEAD"]
brew "optipng"
brew "pngquant"
brew "postgresql", restart_service: true
brew "postgis"
brew "re2"
brew "redis", restart_service: true
brew "ripgrep"
brew "terminal-notifier"
brew "tmux"
brew "ttygif"
brew "unrar"
brew "vim", args: ["HEAD"]
brew "watchman"
brew "wxmac"
brew "yarn"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "zaquestion/tap/lab"
cask "android-platform-tools"
cask "android-sdk"
cask "chromedriver"
cask "iina"
cask "java8"
cask "vlc"
