#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# ignore these apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Little Snitch$" manage=off
# yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^About This Mac" manage=off
yabai -m rule --add app="^Activity Monitor" manage=off
yabai -m rule --add app="^App Store" manage=off
yabai -m rule --add app="^Calendar" manage=off
yabai -m rule --add app="^Calculator" manage=off
yabai -m rule --add app="^Clock" manage=off
yabai -m rule --add app="^Contacts" manage=off
yabai -m rule --add app="^Books$" manage=off

yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^1Password 7$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off


# global settings
# focus window that your mouse hovers on (disabled due to right click bugs)
yabai -m config focus_follows_mouse          off
yabai -m config mouse_follows_focus off
# move mouse to focused window


yabai -m config mouse_modifier fn

yabai -m config window_placement             second_child

# floating windows always stay on top
yabai -m config window_topmost               on
# enable borders
yabai -m config window_border                on
# no clue what this is
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
# don't automatically rebalance windows
yabai -m config auto_balance                 off
# swap windows if moved with mouse
yabai -m config mouse_action1                move
# resize windows if resized with mouse
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9



yabai -m config window_animation_duration 0.0

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   3



# SIP Required
# prevent border from being under the active window
yabai -m config active_window_border_topmost on
yabai -m config window_shadow                float
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xffff3050
yabai -m config normal_window_border_color   0xffaaaaaa

