#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# SPACES
yabai -m space 1 --label 1_work
yabai -m space 2 --label 2_webs
yabai -m space 3 --label 3_email
yabai -m space 4 --label 4_code
yabai -m space 5 --label 5_temp
yabai -m space 6 --label 6_temp
yabai -m space 7 --label 7_temp
yabai -m space 8 --label 8_temp
yabai -m space 9 --label 9_other

yabai -m config --space 5_temp layout float
yabai -m config --space 6_temp layout float
yabai -m config --space 7_temp layout float

yabai -m space 1_work --display 1
yabai -m space 2_webs --display 1
yabai -m space 3_email --display 1
yabai -m space 4_code --display 1
yabai -m space 5_temp --display 1
yabai -m space 6_temp --display 1
yabai -m space 7_temp --display 1
yabai -m space 8_temp --display 2

#======= Rules =======================
yabai -m rule --add app="^(Spark|Outlook)$" space=1_work
yabai -m rule --add app="^(Microsoft Edge|Safari|Google Chrome)$" space=2_webs
yabai -m rule --add app="^(kitty)$" space=3_email
yabai -m rule --add app="^(Code)$" space=4_code
yabai -m rule --add app="^(Lightroom Classic|HitPaw Photo AI|Adobe Photoshop 2024|Topaz Photo AI|Python)$" space=5_temp
yabai -m rule --add app="^(Maps|Gemini 2|UserNotificationCenter|1Password 7|Creative Cloud|Docker Desktop|Preview|WhatsApp|System Settings|Podcasts|CleanMyMac X|Navicat Premium|1Password 7|App Store|Dash|Activity Monitor|Calculator|Finder|Notes|Invoice Pro|Fork|Books|IINA|VLC|Microsoft Excel|Microsoft Word|Font Book)$" space=6_temp
yabai -m rule --add app="^(Slack|zoom.us|Discord|Skype)$" space=7_temp
yabai -m rule --add app="^(Firefox|X|Spotify)$" space=8_temp #opacity=1.00

# ignore these apps
yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Little Snitch$" manage=off
yabai -m rule --add app="^About This Mac" manage=off
yabai -m rule --add app="^Activity Monitor" manage=off
yabai -m rule --add app="^Calendar" manage=off
yabai -m rule --add app="^Calculator" manage=off
yabai -m rule --add app="^Clock" manage=off
yabai -m rule --add app="^Contacts" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
# firefox PIP
#yabai -m rule --add app="^Firefox$" title="^$" manage=off layer=below
yabai -m rule --add app="^Spark$" subrole="AXDialog" manage=off

# Do not manage windows with certain titles eg. Copying files or moving to bin
yabai -m rule --add title="(Copy|Bin|About This Mac|Info)" manage=off
yabai -m rule --add subrole="^AXSystemDialog$" manage=off mouse_follows_focus=off
yabai -m rule --apply 
yabai -m config                              \
    external_bar                off:41:0     \
    mouse_follows_focus         off          \
    window_zoom_persist         on           \
    focus_follows_mouse         off          \
    window_placement            second_child \
    window_shadow               float        \
    window_animation_duration   0.05         \
    window_animation_easing     ease_in_out_quint \
    window_opacity_duration     0.0          \
    active_window_opacity       1.0          \
    normal_window_opacity       0.95         \
    window_opacity              on           \
    insert_feedback_color       0xaad75f5f   \
    split_ratio                 0.50         \
    split_type                  auto         \
    auto_balance                off          \
    top_padding                 2            \
    left_padding                2            \
    right_padding               2            \
    bottom_padding              2            \
    window_gap                  2            \
    layout                      bsp          \
    mouse_modifier              fn           \
    mouse_action1               move         \
    mouse_action2               resize       \
    mouse_drop_action           swap

echo "yabai configuration loaded.."